### ISSUE TITLE
Discount no longer works on RX

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#1]
When you discount an RX Item it does not get discounted - 
![image](https://user-images.githubusercontent.com/61169385/88681116-384b2080-d0bf-11ea-943a-b9ee3623cde9.png)

**Comment by dyuan-boxlabs** [comment]
This requires an add rx by rxnumber textfield as there is 1500ms assumption for entering RxNumber

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/36
