### ISSUE TITLE
Oepn/ Close Cash

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#10]
**User information:**
 - Store login name:  user_Church

**Describe the bug**
Ok the language needs to change
- Open Cash should be called "Enter Current Float"
- Close Cash should be called "End of Day Settlement"
once a user has entered current float it should never prompt them to do that again unless the EOD Settlement has been done.

**Comment by pwang-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/38
