### ISSUE TITLE
[FEATURE-REQ] Add $ formating, add ability to select all for unpicked up RX

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#102]
![image](https://user-images.githubusercontent.com/61169385/92486295-e9ae9d00-f1b9-11ea-8486-1e84b4f64a5c.png)

Add $ formating, add ability to select all for unpicked up RX, should be called "Add RX for Pickup" 

![image](https://user-images.githubusercontent.com/61169385/92486432-1793e180-f1ba-11ea-9a61-8929b10fe09a.png)
bottom button should be "Select"

**Comment by nidhirbstpl** [comment]
fixed in 
https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/b618366252fcd7516b50df572d06987d69e82d89

https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/f80fd5ab804957b491ae9be3a03236ae6546f977
