### ISSUE TITLE
[FEATURE-REQ] DISCOUNT needs to show on the paper RECEIPT

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#103]
discount needs to show on the paper receipt

**Comment by pwang-boxlabs** [comment]
its already shown no? 
![image](https://user-images.githubusercontent.com/65085660/92566132-c0d5e880-f249-11ea-9f28-ce1e7da10938.png)

**Comment by mikedemian** [comment]
Looks good - please remove all the underlines. @pwang-boxlabs
