### ISSUE TITLE
[BUG] [URGENT] Patient not searchable

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#108]
![image](https://user-images.githubusercontent.com/61169385/92512339-a6b1f100-f1dc-11ea-9ed0-39ea0256f2c0.png)

this patient john mcbain not searchable but he is our patient and can be found in kroll database at dundas

**Comment by pwang-boxlabs** [comment]
related to the syncing problem

**Comment by mikedemian** [comment]
This person was created in Kroll not Box - what's the fix here?

**Comment by dyuan-boxlabs** [comment]
![image](https://user-images.githubusercontent.com/65084919/94290981-f99fde00-ff28-11ea-9c06-0bf5ae40f2d3.png)

patient list wasn't syncing - i think that was the issue. This looks to be fixed
