### ISSUE TITLE
[BUG] rx does not show for patient 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#110]
this is at dundas- see below screenshots

![image](https://user-images.githubusercontent.com/61169385/92603608-7ff7c700-f27d-11ea-9a5b-530d1086cd10.png)

this user has RX that are not shown.

**Comment by dyuan-boxlabs** [comment]
![image](https://user-images.githubusercontent.com/65084919/94290788-ab8ada80-ff28-11ea-93ff-25f80dc64738.png)

**Comment by dyuan-boxlabs** [comment]
might have went to the wrong profile

**Comment by dyuan-boxlabs** [comment]
@mikedemian
