### ISSUE TITLE
[BUG] In Medscheck doctor selection page- each doctor should only show one time

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#111]
See attached

![image](https://user-images.githubusercontent.com/61169385/92613761-517fe900-f289-11ea-97f5-88ab0ff88ac9.png)

**Comment by nidhirbstpl** [comment]
Fixed in commit https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/92/commits/b5e0d1243373a51bd085f0ff8fb92255108c0d4d
