### ISSUE TITLE
[FEATURE-REQ] line these boxes up pleaes

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#113]
![image](https://user-images.githubusercontent.com/61169385/92625989-56e43000-f297-11ea-9fc0-96d2aa34fdf9.png)

**Comment by nidhirbstpl** [comment]
Fixed in commit https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/92/commits/be246e060904e9b23d6d00d401c3aa00f0f47226
