### ISSUE TITLE
[FEATURE-REQ] Dashboard Fixes

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#116]
1.  default number of rows - 30
![image](https://user-images.githubusercontent.com/61169385/93229956-25f77580-f745-11ea-949e-ec9ca5a9f59c.png)

2.  Picked Up Rx - filter for only patients who have picked up an RX in the date range specified and are also eligible for a medscheck, Not Picked Up - filter for patients who are due to pick up ready RX's but have yet to pick them up.
![image](https://user-images.githubusercontent.com/61169385/93230032-3dcef980-f745-11ea-9470-d878cca3d33e.png)

**Comment by pwang-boxlabs** [comment]
1: we probably want a better way to adjust this. the length of it should depends on the screen size. i.e. if we use Bathurst POS machine it can probably only fit 20 rows or sth

**Comment by mikedemian** [comment]
Can it be screen resolution dependent. Otherwise we can put it in settings.

**Comment by pwang-boxlabs** [comment]
irrelevant now. using the new ui
