### ISSUE TITLE
[FEATURE-REQ] Flu shot form enhancements

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#117]
1.  This button should be "Next, not Submit"
![image](https://user-images.githubusercontent.com/61169385/93230451-acac5280-f745-11ea-85c2-629130c08015.png)

2.  Patient/Agent name should be automatically filled out, signature is a signature field, similar to medscheck, same with pharmacist signature
![image](https://user-images.githubusercontent.com/61169385/93230515-bfbf2280-f745-11ea-922f-c8920aaa16ea.png)

3.  For this page -  ![image](https://user-images.githubusercontent.com/61169385/93230881-2ba18b00-f746-11ea-91d9-ce217ca00b89.png)

Below image should be a drop down menu - should only be able to select one.  
![image](https://user-images.githubusercontent.com/61169385/93230849-23495000-f746-11ea-9036-9de42b824c31.png)
** for these year the options are listed below - 
![image](https://user-images.githubusercontent.com/61169385/94018584-c588b980-fd7e-11ea-94a5-90ec834fcc0e.png)

Patient Name - OK to leave out as its already , this is redundant.
Route - Always Intramuscular
Site of Administration - Drop down menu with two options - 1- Left Deltoid 2. Right Deltoid  - instead there are two places to enter data
Administering Pharmacist name / ocp # - this was previously asked and doesn't need to be included here.

Epinephrine Treatment - form below should only show if patient clicks checkbox that says "Administered Epinephrine" , otherwise this below section should be hidden.

Dose - default to 0.5mL but allow user to change if necessary.

**Comment by nidhirbstpl** [comment]
![Screen Shot 2020-09-24 at 11 27 50 PM](https://user-images.githubusercontent.com/32067907/94182232-51552f80-febe-11ea-9ede-bb03983da24e.png)
![Screen Shot 2020-09-24 at 11 26 45 PM](https://user-images.githubusercontent.com/32067907/94182251-55814d00-febe-11ea-82c0-999cbd5e2afe.png)

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/123
