### ISSUE TITLE
[FEATURE-REQ] Patient list

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#118]
Can this be ordered by time (I don't want time showing) but i want most recent patient first by time 

![image](https://user-images.githubusercontent.com/61169385/93232894-6ad0db80-f748-11ea-9117-cf6da6dd67b1.png)

**Comment by dyuan-boxlabs** [comment]
same as in unpickedup rx, but component rendered doesnt have time

**Comment by dyuan-boxlabs** [comment]
@jonwang2000 pretty sure this is already sorted by time, double check
