### ISSUE TITLE
Indicator  (green or red) to indicate weather or not you are currently connected to sync server

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#12]
**Is your feature request related to a problem? Please describe.**
We are constantly getting error messages and I've been able to figure out that its because for whatever reason we lose connection to the sync server - it would be helpful to know in advance so we can log in / out or understand why we are getting errors.

**Describe the solution you'd like**
indicator button top right green or red to let us know if we are connected to sync server.

**Comment by dyuan-boxlabs** [comment]
under review https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/23
