### ISSUE TITLE
[FEATURE-REQ] Flu Vaccine Form

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#120]
Add a "No to all" button or checkbox.

![image](https://user-images.githubusercontent.com/61169385/93233875-97392780-f749-11ea-85cb-53fb96ff8641.png)

**Comment by mikedemian** [comment]
Also - when I enter data below and go to the next tab it is removed when I go back

![image](https://user-images.githubusercontent.com/61169385/93252525-a2994c80-f763-11ea-913c-e4fb428af13b.png)


Please make sure all screening questions are marked required

Also, submit and save for later do NOTHING - should save in patient profile like the medscheck does.

**Comment by pwang-boxlabs** [comment]
related to  https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/117

**Comment by nidhirbstpl** [comment]
![Screen Shot 2020-09-24 at 11 28 03 PM](https://user-images.githubusercontent.com/32067907/94182882-3e8f2a80-febf-11ea-9f79-1d1dbb4e77c1.png)

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/123
