### ISSUE TITLE
[FEATURE-REQ] Add Edit Product to List of what you can do to item - 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#121]
Add - "edit product' ; this would take you to product page where you can make changes to product, taxable, non-taxable , price etc. 

![image](https://user-images.githubusercontent.com/61169385/93235577-c486d500-f74b-11ea-9141-ccec428394a3.png)

**Comment by nidhirbstpl** [comment]
![Screen Shot 2020-09-17 at 8 54 46 AM](https://user-images.githubusercontent.com/32067907/93416697-eb681700-f8c3-11ea-86ff-10feb8829818.png)
![Screen Shot 2020-09-17 at 8 54 59 AM](https://user-images.githubusercontent.com/32067907/93416705-eefb9e00-f8c3-11ea-9655-1e72f9637c6d.png)

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/4406b01d3374df7188ca56229654e2115255d088
