### ISSUE TITLE
[URGENT] Narcotic RX comes up for regular item

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#122]
when this upc (4987188507278) is scanned - the below comes up

![image](https://user-images.githubusercontent.com/61169385/93236296-a8cffe80-f74c-11ea-9abc-6334dcf5e8e7.png)

this is "Salonpas Patch" for 5.99 plus tax.

**Comment by pwang-boxlabs** [comment]
think we brought this up earlier but it was never resolved. We need your help to find a way to distinguish between GTIN13 and krolls barcode format (also 13 digits)

**Comment by mikedemian** [comment]
Can you explain how you currently can't ell if something is an rx or a regular product?

**Comment by pwang-boxlabs** [comment]
there's just no way to distinguish what's if the barcode is for Kroll Rx or over the counter product if the UPC is 13 digits. The current code just assume all the scanned items are Kroll Rx if it's 13 digits barcode. We'll prob have to go through more products to find a certain way to distinguish these two.

**Comment by mikedemian** [comment]
There must be a way to distinguish. Can you tell me what criteria you currently use to discern between rx and product? That will help me find ways to differentiate.
