### ISSUE TITLE
[FEATURE-REQ] Remove these unnecessary buttons

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#124]
please see image - for cleaner look please remove all these - they are unnecessary and redundant 

![image](https://user-images.githubusercontent.com/61169385/93248867-74653e00-f75e-11ea-9146-09845ecf0c78.png)

Find RX, Change Quantity, Add - all unnecesssary as you can do all this from other places - just looks cluttered.

**Comment by dyuan-boxlabs** [comment]
comment out buttons

**Comment by dyuan-boxlabs** [comment]
@jonwang2000
