### ISSUE TITLE
[BUG] This happened almost for no reason that I could see.

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#125]
![image](https://user-images.githubusercontent.com/61169385/93256169-f2c6dd80-f768-11ea-9d17-bcf466bd6a7e.png)

had to exit and open again

**Comment by pwang-boxlabs** [comment]
is there any pattern that you can identify?

**Comment by dyuan-boxlabs** [comment]
ill debug this a big, i will close it if i cant reproduce it

**Comment by dyuan-boxlabs** [comment]
cant recreate it, closing
