### ISSUE TITLE
[FEATURE-REQ] Clinical Intervention Dashboard Boxes *IMPORTANT, REVENUE GENERATING*

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#127]
![image](https://user-images.githubusercontent.com/61169385/93258581-8b129180-f76c-11ea-850b-73f075c0fdc2.png)

Should be called "Clinical Interventions" instead of "Dashboard"

Boxes at top should be from left to right 

1. Medscheck Eligible
          Two Kinds
               Yearly - have NOT had an annual medscheck (93899979) in the past 365 days  
               Follow-up  - have a had an annual (DIN - 93899979) or diabetic medscheck (93899988) in the past 1 year but not in the last 3 months.

2. Naloxone Kit Eligible 
         Two Kinds - 
               Initial :
                  - must be on an opioid medication (any RX that starts with N) 
                  - NOT had Naloxone Kit (93877252)  or Initial Naloxone Kit (DIN: 93877251) ever in their history at the pharmacy
               Replacement
                  - must be on an opioid medication (any RX that starts with N) 
                  - NOT had Naloxone Kit (93877252)  or Initial Naloxone Kit (DIN: 93877251) in the past 4 months.

3. Pharmaceutical Opinion 
                  Criteria - to be provided , but leave place for it.
4. Flu Shots
                  Criteria - have not had flu shot yet (DINs to be provided, and change yearly)
                               - due to come in to pharmacy in date range
5. Smoking Cessation 
                  Criteria - have responded YES to smoking any amount during a medscheck
6. Refill Reminder 
                 Criteria - RX due to be filled in that date range 

** # of ppl Eligible / # Completed should both be in the box  
** user should be able to select one or more boxes - ie should be able to see all medschecks, and all smoking cessation at the same time.   

I've attached a small screenshot to give an idea of what it should look like

![image](https://user-images.githubusercontent.com/61169385/93262043-94522d00-f771-11ea-9546-cf838e90bab0.png)

**Comment by dyuan-boxlabs** [comment]
waiting for front end UI design

**Comment by dyuan-boxlabs** [comment]
smoking cessation https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/161 https://github.com/BoxLabsGithub/Waiveless-backend/pull/74

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/161

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/Waiveless-backend/pull/74
