### ISSUE TITLE
[BUG] RX UNPICKED UP methadone, suboxone etc

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#128]
you only show each RX drug once (even if its repeated) - this works all the time except in one instance for unpicked up RX - clients on Methadone will pick up 7 RX for Methadone in one day - these are 7 seperate RX that are filled and need to all be cashed out - but only shows one instance.  For RX Not Picked Up it should show all RX that were not cancelled - even if filled multiple times as these all need to be "cashed out" - does that make sense? let me know if it doesn't.

This can also happen with Suboxone - essentially each RX that is filled should show in RX PICKUP. 

![image](https://user-images.githubusercontent.com/61169385/93364806-fe70dd80-f816-11ea-808c-75f7deb3e6d2.png)

![image](https://user-images.githubusercontent.com/61169385/93365114-61627480-f817-11ea-91be-e63b238a9b3c.png)

**Comment by pwang-boxlabs** [comment]
where are you showing it? do we show this in the rx history tab and un-group it if it's not picked up?

**Comment by mikedemian** [comment]
this is for the "unpicked up rx" box - its in the image above.  Any Rx that has NOT been picked up shows there.
