### ISSUE TITLE
[FEATURE-REQ] Add REFRESH button in unpicked up RX list 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#129]
It takes 5 mins or so before the RX shows up in the unpicked up RX list for customers - can we add a manual refresh button?

![image](https://user-images.githubusercontent.com/61169385/93379382-bf995280-f82b-11ea-8f92-1404f2549644.png)

**Comment by dyuan-boxlabs** [comment]
this is partially fixed, when you click into this table the rx is synced once, ill add a refresh button just in case
