### ISSUE TITLE
[FEATURE-REQ] Right after initial Log In 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#134]
when you log in the pop up to open cash comes up for a few seconds before going away if you have already opened the cash - this is confusin because user will just hit confirm or something .... does this make sense?

**Comment by dyuan-boxlabs** [comment]
Ask Paul for clarification

**Comment by dyuan-boxlabs** [comment]
@setupotnis
