### ISSUE TITLE
[FEATURE-REQ] Logo Issue

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#141]
two things - aesthetics only
1- need higher res logo top left - looks pixelated sometimes
2- can we please have app logo for desktop etc 

![image](https://user-images.githubusercontent.com/61169385/94601614-b8c60300-0261-11eb-860f-dbf0a68f9bfb.png)

**Comment by setupotnis** [comment]
changing logo to:

![image](https://user-images.githubusercontent.com/46113818/94928683-10e34c00-0492-11eb-91c9-2f5bf244fa0d.png)

**Comment by setupotnis** [comment]
updated:

![image](https://user-images.githubusercontent.com/46113818/94929403-0c6b6300-0493-11eb-9ca9-9f9bf5e822be.png)

**Comment by setupotnis** [comment]
changed logo to a curved border with less white padding
