### ISSUE TITLE
[BUG] Proper typing for thunk action dispatchers and work around for middleware dispatchers

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#151]
A few scenarios below causes ts errors, the core issue is that Dispatch is typed to only expect synchronous actions with a type argument.

![image](https://user-images.githubusercontent.com/65084919/94843752-25203e00-03eb-11eb-887c-d0c99e299e4b.png)

This fails whenever we use dispatch: Dispatch to use with thunk or middleware calls, and when its used with bindActionCreators.

Scenario 1: Using Dispatch on another thunk 

![image](https://user-images.githubusercontent.com/65084919/94843916-66b0e900-03eb-11eb-929c-ea78d30fd81f.png)

Scenario 2: Using Dispatch on a middleware call

![image](https://user-images.githubusercontent.com/65084919/94843959-76c8c880-03eb-11eb-9ff3-212cad4700fb.png)

Scenario 3: calling a thunk in tsx code (after bindActionCreators)

![image](https://user-images.githubusercontent.com/65084919/94844041-9c55d200-03eb-11eb-8a7c-0f691d1d3cd7.png)

For scenario 2, we can use a workaround where we add a dummy type param

![image](https://user-images.githubusercontent.com/65084919/94844093-b4c5ec80-03eb-11eb-8f79-06d1e662a17e.png)

For scenario 1, we can overload the Dispatch definition to accept other thunks,
For scenario 3, we need a custom type and force cast the return value of bindActionCreators

**Comment by jonwang2000** [comment]
For reference, the Thunk issues are related to https://github.com/reduxjs/redux-thunk/pull/224 and https://github.com/reduxjs/redux-thunk/issues/299 - they should be fixed via `redux-thunk`'s own typing but they haven't released a new npm release in 2 years. Still exploring options.
