### ISSUE TITLE
[FEATURE-REQ] patient profile aesthetic improvement

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#155]
![image](https://user-images.githubusercontent.com/61169385/95005692-d8df2480-05c9-11eb-963c-bd1ac6339b9b.png)

there is no need to have RX History header below RX History button - the search box should be moved up and it should be right aligned beside the "add" button.

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/241/commits/218e145fee8470902382a8fb52429ee8eba6e29c
