### ISSUE TITLE
[[URGENT] submit button for medscheck does it work

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#156]
**Describe the bug**
Unable to submit medscheck. Please let me know and fix ASAP. 

clear and concise description of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/Waiveless-backend/pull/69
