### ISSUE TITLE
[FEATURE-REQ] Remove the boxes at the top - and make them smaller icons

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#159]
![image](https://user-images.githubusercontent.com/61169385/95215568-19ec5a00-07bf-11eb-8aa7-66cbb4dcda77.png)

can these just be circles - green or red in the login box below logout - these look so ugly here

**Comment by pwang-boxlabs** [comment]
make it a stand alone component with its own mapstatetoprops/mapdispatchtoprops rather then nested in the nav bar for performance
