### ISSUE TITLE
[BUG] Access to Medscheck from POS - has no drugs for patients

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#160]
if you start a medscheck via POS there is no drugs listed for patients, but if you start it from the profile it works fine

**Comment by dyuan-boxlabs** [comment]
getPatient(PAT_ID) not being called due to caching, have useEffects in MedsCheck component index actually check the PAT_ID in rxes in patient duck and if not present or wrong fetch patient info again

**Comment by jonwang2000** [comment]
Looked into it and it seems the MaterialTable's `PageSize` option isn't updating properly, even when the RxHistTable component is rerendering with the correct data (and length of that data), even if the pageSize option is set to use a useState variable - not sure why after poking around.

**Comment by jonwang2000** [comment]
Can by bypassed atm by using the dropdown to change page size to any of the options, codewise we could just set pageSize to 20 (as we do for all other tables).

**Comment by dyuan-boxlabs** [comment]
"Seems to be a bug related to the material ui tables, swapped from adaptive data.length to just 20 like other tables"
