### ISSUE TITLE
[FEATURE-REQ] Sig needs to be included in new column in med profile

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#165]
the Sig (or directions) need to be included in new column in patient profile - 

![image](https://user-images.githubusercontent.com/61169385/95382145-34a1fa00-08b7-11eb-8aba-d5e63d8feded.png)

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/197/commits/a02df5b0b155937a705a8d22aaa33d71e9df8d9b
