### ISSUE TITLE
[BUG] Quantity Left and Patient Pays Fields

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#166]
![image](https://user-images.githubusercontent.com/61169385/95384639-e68ef580-08ba-11eb-8a72-87442f3ffea6.png)

quantity left field is always zero - should be however many pills are remaining.

also the patient pays column isn't formatted for currency

**Comment by pwang-boxlabs** [comment]
quantity left info isn't really tracked
