### ISSUE TITLE
[FEATURE-REQ] at end of medscheck and others

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#167]
After hitting submit on a medscheck flu shot or Covid test came we just have the user brought back to the page they were on prior. Weather that be POS or profile or whatever. I think that's better than having the option at the end.  More intuitive. Less thinking. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dyuan-boxlabs** [comment]
i think this was checked in by nidhir
