### ISSUE TITLE
[BUG] medscheck - cant see or edit what you typed

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#169]
see below - long sentence can't be edited 

![image](https://user-images.githubusercontent.com/61169385/95489102-658c3880-0964-11eb-87e5-81653c95cf2e.png)

why doesn't patient name and birthday show up anymore here? when you go back into medscheck
![image](https://user-images.githubusercontent.com/61169385/95489218-953b4080-0964-11eb-9dae-31e3e4039010.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/compare/master...dyuan

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/163
