### ISSUE TITLE
Pay Balance - not working

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#17]
**Describe the bug**
After you pay balance - the balance is still there

![image](https://user-images.githubusercontent.com/61169385/88837139-d2859400-d1a5-11ea-9131-065edfe2cf2e.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/Waiveless-backend/pull/21

**Comment by dyuan-boxlabs** [comment]
UI probably needs a rework for this, should lead to POS checkout screen or something
