### ISSUE TITLE
Error - on reports page - when you click into "end of shift summary"

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#175]
![image](https://user-images.githubusercontent.com/61169385/97184359-31db4c00-1775-11eb-8b73-ec1d1e3e1ed1.png)

**Comment by mikedemian** [comment]
Also, why does it default to patient "Angelo Stamadianos" - there is no patient parameters at all for this report.

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/197/commits/b4b187aeeb9685fef142c0eafded96cc215d142f

https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/197/commits/ec9fa55f5b92282a06cfe0ae987c1a8aa8ff4450
