### ISSUE TITLE
[BUG] need a CANCEL button here.

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#178]
![image](https://user-images.githubusercontent.com/61169385/97191274-18d69900-177d-11eb-9b0d-286715702fd8.png)

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/197/commits/3855e229fc0661aeb77bce92eafcfc476e2e4b48
