### ISSUE TITLE
[FEATURE-REQ] Can patient REFRESH be in all patient search screens

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#182]
this screen is from POS add patient

![image](https://user-images.githubusercontent.com/61169385/97742899-4728e100-1abb-11eb-9caa-a7d19f1de349.png)

**Comment by nidhirbstpl** [comment]
fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/217/commits/2545449edcf9f9c3f431fa4f81e100dc2aefef14
