### ISSUE TITLE
[FEATURE-REQ] search boxes are not right aligned all across the app - looks off

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#183]
see images below - right align the search box please 

![image](https://user-images.githubusercontent.com/61169385/97768988-89731200-1afd-11eb-8caa-744965d4f3a7.png)

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/208/commits/ce5e471b2810d234170916a38479a5dc59653490
