### ISSUE TITLE
[BUG] FOR LAUNCH

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#186]
Can't select same date start and end date can't be the same - this report should default to same day
 
[image](https://user-images.githubusercontent.com/61169385/97781503-439c6500-1b62-11eb-9261-f318c0d4ad71.png)

**Comment by mikedemian** [comment]
![image](https://user-images.githubusercontent.com/61169385/97781591-e94fd400-1b62-11eb-9239-fe5b909dc911.png)

![image](https://user-images.githubusercontent.com/61169385/97781601-fc62a400-1b62-11eb-96e2-6dc7db90df28.png)

why is total paid zero? - can you have it so if you click into the transaction you can see the detail same as from patient profile -i t goes to last page of checkout - also why is customer's name not there? and we can remove the "note" column, 

need to be able to see details  eg - this transaction looks off
![image](https://user-images.githubusercontent.com/61169385/97781668-60856800-1b63-11eb-9d9f-aafc10b3875e.png)

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/226/commits/7da702eafe43a031fda15d88edd32b9e13666e58
