### ISSUE TITLE
[URGENT] CUSTOMER STATEMENT

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#187]
![image](https://user-images.githubusercontent.com/61169385/97781557-b279be00-1b62-11eb-89a4-0c462ee3bb0c.png)

this need to be corrected -

**Comment by pwang-boxlabs** [comment]
?

**Comment by mikedemian** [comment]
look at the statements why is the same item appearing so many times never been purchased never been put on hold - shouldn't be there at all.

**Comment by pwang-boxlabs** [comment]
thats just diff transactions. you can see that they have different transaction IDs.  i supposed u used that for testing -- i thought u said u wanted to show all the transaction history in the same table- thats the purchase history.

**Comment by mikedemian** [comment]
I do - I'll test from scratch to make sure but these items were NOT put on account they were scanned and then deleted so they shouldn't show - i'll do it again now to test.

**Comment by mikedemian** [comment]
Ok - seems like its working but I need to do more testing
