### ISSUE TITLE
[URGENT] 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#189]
changed to patient Brad Duthie, from Michael Demian but still Michael Demian's patient documents are listed here - didn't update

![image](https://user-images.githubusercontent.com/61169385/97782085-e1ddfa00-1b65-11eb-90a6-ff4dd3a6b2e2.png)

**Comment by mikedemian** [comment]
Also Brad Duthie appears in list for Medscheck but he just had one

![image](https://user-images.githubusercontent.com/61169385/97782540-6af63080-1b68-11eb-81d5-e5e4ec3388ac.png)

![image](https://user-images.githubusercontent.com/61169385/97782556-83fee180-1b68-11eb-8dee-078349d03060.png)

For now for Medscheck  - criteria should be 1) currently on 3 or more meds     2) has not had a medscheck DIN 
![image](https://user-images.githubusercontent.com/61169385/97782582-b3155300-1b68-11eb-9d2e-f63aaa7dc7d6.png) in the past 365 days.

**Comment by mikedemian** [comment]
Options for below circled filter should be 1) Pending    2)Completed   3) All

**Comment by nidhirbstpl** [comment]
Options for below circled filter should be 1) Pending 2)Completed 3) All
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/213/commits/ac51ff0e6b13031601924600f90e0748779bc205
