### ISSUE TITLE
[URGENT] Non-Taxable items in POS

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#191]
can we auto update non taxable items - today on a call we can go through catalogue and we can figure out where taxable status is

Ensure is NON-Taxable

Advil Cold and Sinus is TAXABLE

i'm sure its in the Catalogue

**Comment by mikedemian** [comment]
![image](https://user-images.githubusercontent.com/61169385/97786900-04334000-1b85-11eb-9e4f-0cdc30129b3a.png)

all these items are non-taxable

**Comment by mikedemian** [comment]
the below items are taxable

![image](https://user-images.githubusercontent.com/61169385/97786922-2331d200-1b85-11eb-89aa-3ab8f42daeb5.png)

**Comment by pwang-boxlabs** [comment]
@dyuan-boxlabs   caused by fillwarepos migration overwriting the catalgue indicator
