### ISSUE TITLE
[URGENT] app.boxlabs.ca

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#193]
when signing up client - two options are - 1) role1   2) role2  - can that be 1) Owner 2) Pharmacist  3) Technician/Assistant 

Also for store inforation need to add PROVINCE

Also - please make a note that username (email) is case sensitive because email is usually note case sensitive 

I tested out multiple stores and it all works

**Comment by pwang-boxlabs** [comment]
owner is unique. you can't have multiple owners. we only support only owner and users permissions right now

**Comment by pwang-boxlabs** [comment]
add province to address when user address
