### ISSUE TITLE
[URGENT] COVID TEST FORM PDF and App Form

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#194]
The order of the questions on the pdf form needs to match the order on the app - please just re-order the questions to match the pdf attached. 
[box-covid-screening-19248-m74nOvUJ5ooW-.pdf](https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/files/5471176/box-covid-screening-19248-m74nOvUJ5ooW-.pdf)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/205
