### ISSUE TITLE
[URGENT] COVID REQ FORM

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#195]
see attached - let me know if not clear 
[CCF_000001.pdf](https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/files/5471194/CCF_000001.pdf)

**Comment by mikedemian** [comment]
also - why are these slightly off?
![image](https://user-images.githubusercontent.com/61169385/97807447-ddc9df00-1c2e-11eb-963b-2d8f02e589d7.png)

**Comment by dyuan-boxlabs** [comment]
fixed by marios
