### ISSUE TITLE
[URGENT] NOT ALL PROFILE ITEMS SYNCING

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#196]
![image](https://user-images.githubusercontent.com/61169385/97807226-a1e24a00-1c2d-11eb-8624-a700edfea6bf.png)
![image](https://user-images.githubusercontent.com/61169385/97807230-a6a6fe00-1c2d-11eb-98e9-bd1e1c2e78b2.png)

phone number, and odb info not syncing.

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/sync_server/commit/5511e5d00e6e16513f918f094b4149a591c48966
