### ISSUE TITLE
[FEATURE-REQ] when you click into signature box auto expand - instead of just the "expand button"

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#197]
![image](https://user-images.githubusercontent.com/61169385/97807298-0a312b80-1c2e-11eb-8647-570bc3b1ac6c.png)

**Comment by dyuan-boxlabs** [comment]
white space on left and right signature is not usable signature space - either make it usable or remove it @nidhirbstpl

**Comment by nidhirbstpl** [comment]
Fix white-space issue in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/217/commits/64173080e101adf3d1466a4d3d11db6a82088ea3

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/237/commits/9c2be257bbc3f1fc2768e73a7196c7fb7dea7dff
