### ISSUE TITLE
[URGENT] Flu Shot PDF - See attached

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#199]
please see attached 

![image](https://user-images.githubusercontent.com/61169385/97807398-76ac2a80-1c2e-11eb-9eb6-7350d61f0e98.png)

what is checked off is "i want my child to receive the vaccine" instead of "i want to receive the vaccine"

also health card number is missing

![image](https://user-images.githubusercontent.com/61169385/97807424-a9562300-1c2e-11eb-8c85-b9e98fd65d9c.png)

also these two questions are not checked off - i've told aaron to include them but i'm not sure if he has yet

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/199
