### ISSUE TITLE
[URGENT] Unpicked up Rx does not handle multiple patients use case

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#201]
**Describe the bug**
Have two patients in POS and unpicked up rx does not work correctly.

1) One patients rxes show up on the other patients unpicked up table
2) Going back and forth between unpicked up rx dialog causes rxes already selected to disappear
3) Selecting patient 2's rxes sometimes causes the other patient's rxes to disappear from checkout

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nidhirbstpl** [comment]
Fixes https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/213/commits/25b8ae2728db5fbe98622f0cf66a45da64cb9ba9

**Comment by nidhirbstpl** [comment]
test and fix remove rx from list issue in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/217/commits/e6a37b0d7c4a4f3109799d26e4857a4dd0eb8648
