### ISSUE TITLE
[BUG]EOS Details Report Receipt

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#208]
should also show total payment information and be able to reprint the receipt 
![image](https://user-images.githubusercontent.com/65085660/98165019-285b8d80-1eb3-11eb-9f5c-bf17d3058b30.png)

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/226/commits/311ee1fd196b78ecf14c1bc7cbd951883be2bada
