### ISSUE TITLE
[FEATURE-REQ] dashboard shows medscheck type: annual vs follow up. naloxone: init vs refill

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#211]
add another column that shows whether medscheck and naloxone is annual/ follow up and whether naloxone is init or refill. 
you can distinguish the two by looking at the data return. they're returned in different arrays from the server

**Comment by nidhirbstpl** [comment]
fixx in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/226/commits/1400c3cf08332dabbb1b2f0c6d86da848718909c
