### ISSUE TITLE
[BUG] dashboard: badge number should change with the status filter

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#212]
![image](https://user-images.githubusercontent.com/65085660/98409591-245d7600-2041-11eb-9db5-9cffffeeffe7.png)

table is empty but the badge number remains unchanged

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/237/commits/88a334e174fc0353b8b741355df5dacb3709155f
