### ISSUE TITLE
[BUG] Doctor phone numbers mismatching

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#219]
![image](https://user-images.githubusercontent.com/61169385/98581263-36345880-228f-11eb-8f70-713fb9e64951.png)

![image](https://user-images.githubusercontent.com/61169385/98581425-75fb4000-228f-11eb-872d-b15c9578874d.png)

can you just default to office one

**Comment by dyuan-boxlabs** [comment]
need to remigrate Doctor addr info

Kroll
- addresses can be linked to specific fax/phone
- phone numbers not linked to any addresses

Fillware
- no link, no custom descriptions
