### ISSUE TITLE
[BUG] two bugs in pick up queue

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#220]
- Holds and cancelled rx show up in pickup queue. They should not as they are not ready for pick up
- please add auto patient list refresh in pick up queue screen when you go to screen

User information:**
 - Store login name: [e.g. user_Bathurst, user_Church]
 - Patient name (if applicable)
 - Rx number (if applicable)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dyuan-boxlabs** [comment]
- Add enums to status which reflects all statuses in Kroll
- Inactived flag migrated as is
- Fillware migrated as is, if inactivated, then put in ready/inactive
- Expiry is calculated after the fact
- migrate copyto copyfrom

**Comment by dyuan-boxlabs** [comment]
fix frontend to filter out inactivated

**Comment by dyuan-boxlabs** [comment]
requires re-migration after fix is merged
