### ISSUE TITLE
[FEATURE-REQ] can you move this over a little bit - email is long sometimes

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#222]
![image](https://user-images.githubusercontent.com/61169385/98701761-a2729300-2347-11eb-8c25-11f46cc4dac7.png)

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/244/commits/df94033804e6ec76f02a00157b5d368ace24c18f
