### ISSUE TITLE
[BUG] when you change to completed these green circles should update as well

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#223]
![image](https://user-images.githubusercontent.com/61169385/98703753-db136c00-2349-11eb-9cf9-64c24360f910.png)

**Comment by pwang-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/237/commits/88a334e174fc0353b8b741355df5dacb3709155f
