### ISSUE TITLE
[FEATURE-REQ] Doctor page

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#224]
Display/edit doctor information. 

please work with david about the recent doctor contact info changes. 

you can start working on the component itself. it would work similar to Patient page

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/244/commits/fef1e40c421f51d4c015c387508a1871ad70e170

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/247/commits/349ed13064bf01c4d712fd9fb9be983ff36b0515
