### ISSUE TITLE
[URGENT] you shouldn’t be able to scan out the same rx twice

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#226]
If an rx is marked picked up shouldn't be able to scan it in pos and charge client again cause it was already charged. **

Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dyuan-boxlabs** [comment]
@pwang-boxlabs  dont we already have this change?

**Comment by pwang-boxlabs** [comment]
it gives out an warning but still lets u add it by design i believe.

**Comment by mikedemian** [comment]
Ok - thats fine
you can close this one
