### ISSUE TITLE
mobile app: disable auto logging in upon signup

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#230]
{msg: a verification email has been sent to your inbox} or sth after u sign up. can you disable the auto logging in upon signup and bring the user to the login page and display that popup/snackbar (i think the mobile app already has a snackbar so u can just use that)  ?

**Comment by ajiang-boxlabs** [comment]
https://github.com/BoxLabsGithub/BoxConsumerApp/pull/53
