### ISSUE TITLE
[BUG] covid form - use trade name NOT company name

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#236]
covid form - use trade name NOT company name

also can you allow ability to open the two PDFS from the patient profile and not only from the COVID screen?

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/253

**Comment by dyuan-boxlabs** [comment]
@mikedemian where do we use tradename instead of company name

**Comment by mikedemian** [comment]
In the covid requisition form you put the company name instead of the pharmacy trade name. So for example for Dundas you put Nicholas Drugs - when it should be Metro Drugs.
