### ISSUE TITLE
[BUG] COVID forms use the first rx found for specimen collection for all covid forms

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#243]
logic is as follows:

const rxNum = patientRx.find(rx => rx.DIN === '09858125')?.RxNum || '';

Does not take into account multiple collections for same patient

**Comment by dyuan-boxlabs** [comment]
replace with a dropdown
- entries are rx number followed by fill date
- ordered in reverse (latest on top)
- auto populate with latest entry

- add this info into the Data column of WL_PatDocs
- since this modies Data moving forward, handle the case where this info is not present on older documents
- prompt user to select correct rx for older documents that does not have rx number

**Comment by dyuan-boxlabs** [comment]
@ajiang-boxlabs ping me for more details

**Comment by dyuan-boxlabs** [comment]
- Also add to all other forms including medscheck

**Comment by nidhirbstpl** [comment]
Fix for covid form https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/270/commits/381e737cf4f3cde9ecc2bc3e043dff084034f65a

**Comment by nidhirbstpl** [comment]
Fix for Medscheck & Flushot
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/270/commits/d91527ee0fb6a2173805252fa66cb2d80319e4c3
