### ISSUE TITLE
[FEATURE-REQ] cash close cancel confirmation dialog

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#244]
should the user to confirm cancellation if the user click cancel instead of confirm when for EOD(cash close) report

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/267/commits/8281de120dcb077bc605dfc7864179ba81b7ce74
