### ISSUE TITLE
[BUG] COVID testing form

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#246]
if you complete a covid form for one patient and then go in to do it for a completely diff patient it automatcially keeps the same info that you already had in there - try and let me know if this is not clear.

**Comment by pwang-boxlabs** [comment]
Need to clean up the cached record upon completion.

**Comment by dyuan-boxlabs** [comment]
duplicated https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/253
