### ISSUE TITLE
[FEATURE-REQ] login page

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#247]
can all this just pop up when you click on the logo - just want it to be as clean as possible

![image](https://user-images.githubusercontent.com/61169385/99425585-0a3d5680-28d1-11eb-848c-d168e84c106e.png)

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/265/commits/0ba826db0ed6ab8dd17cace5a27e1fda3ec80522
