### ISSUE TITLE
[FEATURE-REQ] bypass printer option 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#248]
for computers that are not connected to a receipt printr can you provide an option to bypass printing - right now i'm just selecting a pdf printer

![image](https://user-images.githubusercontent.com/61169385/99443233-84c5a080-28e8-11eb-92cc-cbf90adbf1ad.png)

**Comment by pwang-boxlabs** [comment]
Why would they be using the pos system then? Please keep in mind that the cash drawer also wouldn’t open unless it’s connected to the receipt printer
