### ISSUE TITLE
[BUG] unpicked up rx - no longer working

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#249]
all "ready" rx should go in here  - but ever since the categorization update nothing shows up

![image](https://user-images.githubusercontent.com/61169385/99453909-a37d6480-28f3-11eb-8d9f-7fb6d8e052e6.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/249
