### ISSUE TITLE
[BUG] Opening a covid form from patient documents sets the state without clearing it

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#253]
1) Go to random patient -> patient documents -> left hand side open covid test as pdf 
-> go to another patient

The previous patients covid info would be there as it is not cleared.

2) Submit button is sometimes disabled (some state is not being cleared 99% sure)

**Comment by ajiang-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/253
