### ISSUE TITLE
[BUG] for refill reminders all info blank

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#254]
![image](https://user-images.githubusercontent.com/61169385/99566210-99627100-299a-11eb-9da6-506188fd5d0a.png)

please always use BRAND name not generic

![image](https://user-images.githubusercontent.com/61169385/99566301-b9923000-299a-11eb-96f8-6dc8038de2a8.png)

**Comment by jonwang2000** [comment]
Seems to be fixed on current build, closing issue
