### ISSUE TITLE
[FEATURE-REQ] ability to swich between stores from here - see pic

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#257]
should be an option to change store that 'll take you to the page where you can select location

![image](https://user-images.githubusercontent.com/61169385/99579844-bacc5880-29ac-11eb-8454-2c7209b5256d.png)

**Comment by pwang-boxlabs** [comment]
it's safer to just logout and log back in again. This option shouldn't be commonly used because the local sync server is also package in and that's tied to a specific store. Implementing it could potentially introduce more bugs.

**Comment by pwang-boxlabs** [comment]
deprecated
