### ISSUE TITLE
[BUG] UI polish

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#260]
set min width or handle overflow i.e.

![image](https://user-images.githubusercontent.com/65085660/99623966-4371e580-29fb-11eb-8903-909e0487ca11.png)

![image](https://user-images.githubusercontent.com/65085660/99624045-6ef4d000-29fb-11eb-91df-cc1a9a48cd9b.png)

**Comment by pwang-boxlabs** [comment]
also the search bar is covering the transaction tab at the bottom

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/267/commits/1d2f988edf3d403590d9553467b5a525b97488ee

https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/267/commits/db252dc23102baa5e68338c7299cc3bdf5c8cd2c
