### ISSUE TITLE
[BUG] Add styling to the preview select on top right for medscheck

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#265]
![image](https://user-images.githubusercontent.com/65084919/99743013-c1d59280-2aa2-11eb-9635-7f6e723d90af.png)

**Comment by nidhirbstpl** [comment]
Fixed in
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/270/commits/13791d3a696b45ff999fe10f0fe97728b084748c
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/270/commits/1796b97940fd19bfdfedcb88b169e0f476585a22
