### ISSUE TITLE
[BUG] medscheck issues - download medsheck

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#268]
please have ability to open pdfs (each seperate) from profile

![image](https://user-images.githubusercontent.com/61169385/99885572-e5641e80-2c03-11eb-86a2-40badf48bca8.png)

 
![image](https://user-images.githubusercontent.com/61169385/99885588-fa40b200-2c03-11eb-8f25-215325bad66f.png)
can this ability to select from here be on the last page at the bottom - looks very ugly here and not lined up properly.

missing on forms

![image](https://user-images.githubusercontent.com/61169385/99885605-2fe59b00-2c04-11eb-8e7c-7a4007e2e121.png)

![image](https://user-images.githubusercontent.com/61169385/99885613-468bf200-2c04-11eb-8d7d-f8f47c3b18db.png)

**Comment by nidhirbstpl** [comment]
@mikedemian I have already done few optimization for medscheck page in other ticket. Please have a look and let me know if still need to move it on last tab bottom?

![Screen Shot 2020-11-25 at 10 16 27 AM](https://user-images.githubusercontent.com/32067907/100184860-768b0c00-2f08-11eb-892e-05c92c0366dd.png)

**Comment by nidhirbstpl** [comment]
Remaining Fixes in 
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/283/commits/8c7c37865dba057271959649c0045213409bc2d0
