### ISSUE TITLE
[BUG] K&F requires daily updates as they only provide a diff file for the update, need to put K&F updating to the server

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#27]
**User information:**
 - Store login name: [e.g. user_Bathurst, user_Church]
 - Patient name (if applicable)
 - Rx number (if applicable)

**Describe the bug**
As per K&F docs, 'K&F’s daily catalogue update process appends to this file with new additions, changes or deletions. Therefore, your software provider should set up the FTP process to do an APPEND command for orders and follow it with GET command to pick up any catalogue changes and/or ASN's.'

Catalogue can't be offloaded to each front-end instance in this case.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dyuan-boxlabs** [comment]
As K&F catalogue is fixed length, and the fact that non-ascii characters are in the catalogue for rare cases, be aware that this case is handled correctly

![image](https://user-images.githubusercontent.com/65084919/89735743-a504da00-da32-11ea-9aab-06a4e43aaa34.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/Waiveless-backend/pull/28 init check in for azure set up, PM dyuan for storage credentials

**Comment by dyuan-boxlabs** [comment]
Requirements:

Due to K&F requiring the catalogue diff to be removed, the entire catalogue must be stored on the backend rather than the frontend due to multiple users requiring access to the catalogue.

The above check in is the initial check in to use azure blob container to manage the catalogue.

The requirements for this ticket are as follows:
1) Move K&F update catalogue code to backend
2) K&F credentials must be moved over to database as well, create a WL_KnFCredentials, primary key is STORE_ID
3) Have daily jobs at 12am where the catalogue is updated for every entry in WL_KnFCredentials
4) the blob file name will be organized as follows -> `${KF_ID}/catalogue`
5) the request query will contain the KF_ID ie. /api/knf/catalogue?KF_ID=123 and this path will be JWT token protected

**Comment by cwestaway** [comment]
Scheduled catalogue updates can now be performed. Fresh catalogue files and ftp credentials for K&F's production environment can be added when ready.
