### ISSUE TITLE
[FEATURE-REQ]drug ordering preference page

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#271]
![image](https://user-images.githubusercontent.com/65085660/100021629-cbffd580-2daf-11eb-9358-f8d33ec27ca9.png)

![image](https://user-images.githubusercontent.com/65085660/100021736-f356a280-2daf-11eb-9d47-2e601a3a5e81.png)
please make this the center dialog like what we have in the other pages instead of on the side. 

design that akansha did is here.
https://www.figma.com/file/u0i5jHtqQQDn4rvxGM120c/Inventory-Management?node-id=0%3A1

we have all the interchangeable brands and information already.

**Comment by nidhirbstpl** [comment]
fixing in 
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/281/commits/8b1f3479e9f8fc780fae1004134f85727e9963a4
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/281/commits/0bb17b01b10d18020a0ccde463459acd8eec1708

**Comment by nidhirbstpl** [comment]
![Screen Shot 2020-11-27 at 4 48 02 PM](https://user-images.githubusercontent.com/32067907/100443817-64f46080-30d0-11eb-88ee-ec4e3e107ccb.png)
![Screen Shot 2020-11-27 at 4 47 50 PM](https://user-images.githubusercontent.com/32067907/100443820-6887e780-30d0-11eb-8c8d-9549904dd431.png)
