### ISSUE TITLE
[FEATURE-REQ] click on item to get to the interchangeable product page

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#272]
![image](https://user-images.githubusercontent.com/65085660/100023355-d374ae00-2db2-11eb-9713-ac69859a8be5.png)

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/270/commits/fdd5d404b8eca9b07cc8ab293179390ff10c6084
