### ISSUE TITLE
[URGENT] patient now showing up - DUNDAS

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#274]
patient not showing up - tried refresh and searching in both search fields

see attached.
![image (14)](https://user-images.githubusercontent.com/61169385/100139369-5fdbab00-2e5d-11eb-8fe6-5cbc544e3a61.png)
![image (13)](https://user-images.githubusercontent.com/61169385/100139371-5fdbab00-2e5d-11eb-9d19-07f275d379f7.png)
![image (12)](https://user-images.githubusercontent.com/61169385/100139372-60744180-2e5d-11eb-97b3-af1f1a3f94b0.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/304
