### ISSUE TITLE
[FEATURE-REQ] how does user reset password if they forgot it? can that be included in the click box at the top?

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#277]
forgot password link need

**Comment by pwang-boxlabs** [comment]
please be more specific. the user can go to this link to reset their password. 
https://boxapp.azurewebsites.net/web/#/userlogin

**Comment by mikedemian** [comment]
Please provide a forgot password link under the login.
