### ISSUE TITLE
[BUG] all issues related to pre-release

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#287]
1. birthdates on search not populating for all clients only some - see screenshot
![image](https://user-images.githubusercontent.com/61169385/101046062-be381600-354e-11eb-8f36-e01e34833621.png)

![image](https://user-images.githubusercontent.com/61169385/101046096-c55f2400-354e-11eb-8954-1eec43a78c85.png)

2. For medscheck - how do you open "all" from the patient profile page - i don't think you can - is this possible? I only see a way to open it when u click into the medscheck
![image](https://user-images.githubusercontent.com/61169385/101046563-21c24380-354f-11eb-96e5-86049fabc5ea.png)

3. change "print report" to open pdf and remove other two options since they don't work 
![image](https://user-images.githubusercontent.com/61169385/101046975-75349180-354f-11eb-885d-83517f097bc7.png)
also ... lol can we clean up the formatting a little bit of the report looks super shitty..

4. print report, save as pdf, and email pdf in this report all do nothing - no pdf generated here still .
![image](https://user-images.githubusercontent.com/61169385/101047170-a319d600-354f-11eb-8d44-d8b73eff3101.png)

5. for the "end of shift detail report" can we please remove all the stuff at the bottom that does nothing - see image below remove everything below here 
![image](https://user-images.githubusercontent.com/61169385/101047407-d197b100-354f-11eb-8ff0-36c52ee8c7f7.png)

6. search for patient name here only works if you enter full name (customer statement report)- 
![image](https://user-images.githubusercontent.com/61169385/101047527-e7a57180-354f-11eb-8522-a2bb594d0c93.png)

![image](https://user-images.githubusercontent.com/61169385/101047558-ec6a2580-354f-11eb-8188-cb8cfb1551e5.png)

7. print report and all buttons does not work here either .... 
![image](https://user-images.githubusercontent.com/61169385/101047723-0f94d500-3550-11eb-97bf-03292420b7f8.png)
for customer statement

**Comment by dyuan-boxlabs** [comment]
DOB issue requires full remigration of patient profiles, you can sync each patient by going to their profile. Bug where sync was not happening on v0.3.41 has been fixed
