### ISSUE TITLE
[URGENT] ** ADD RX FOR PICK UP **

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#289]
1. We need to eliminate or auto-mark picked up all the RX before a certain date - I think we need to decide on T-7days from install. 
2. Can we add a select all button in image below - for browse RX - so you can search patient name and select all.

![image](https://user-images.githubusercontent.com/61169385/101231648-b1184580-367a-11eb-9847-074744c94128.png)

**Comment by mikedemian** [comment]
also can search box be able to search for patient name or drug name under browse rx? 

Also .. I don't think auto-update works on mac - is this a simple fix?

**Comment by dyuan-boxlabs** [comment]
@mikedemian search and select all are already there?

![image](https://user-images.githubusercontent.com/65084919/101231949-9e067500-367c-11eb-9b10-750e6a6c98e2.png)

**Comment by dyuan-boxlabs** [comment]
![image](https://user-images.githubusercontent.com/65084919/101231971-d0b06d80-367c-11eb-97ef-ddd628ef5642.png)

**Comment by dyuan-boxlabs** [comment]
add t-7 for everything to be marked as picked up is part of migration

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/290

**Comment by dyuan-boxlabs** [comment]
im closing this ticket, #290 addresses T-7 issue and #291 tracks the mac update thing
