### ISSUE TITLE
[BUG] Dundas - please see image

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#29]
![image](https://user-images.githubusercontent.com/61169385/89327742-5c2bda80-d65a-11ea-80ff-aac0eaf1404f.png)
we need  to limit number of characters for generic drug please see this

**Comment by dyuan-boxlabs** [comment]
This is whats displayed for 02437058 though

**Comment by dyuan-boxlabs** [comment]
![image](https://user-images.githubusercontent.com/65084919/89485007-cc775080-d76d-11ea-86d0-27235ac7f21e.png)

**Comment by mikedemian** [comment]
I understand but we can’t let it be that long. We have to limit the characters. 2 lines maximum. I can check what kroll does. But this also messed up the ability to select some drugs etc.
