### ISSUE TITLE
[BUG] no health card showing for this patient

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#292]
1. please see this patient at Dundas - no health card.
2. also email not migrated for patient from kroll for this cleint 

![image](https://user-images.githubusercontent.com/61169385/101282844-57f90080-37a5-11eb-8a36-68cd2f059641.png)

![image](https://user-images.githubusercontent.com/61169385/101282768-ecaf2e80-37a4-11eb-8c42-b9602f9ad015.png)

**Comment by dyuan-boxlabs** [comment]
Fixed in adding resync button in other settings ticket
