### ISSUE TITLE
New Item - Submit button doesn't work

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#3]
![image](https://user-images.githubusercontent.com/61169385/88682729-02a73700-d0c1-11ea-87f0-3254b4fbf163.png)
Submit button does not do anything here - it should go back to the POS .
This was an item that did not have a selling price in the system - everything worked fine but submit button didn't work

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/39
