### ISSUE TITLE
[BUG] payment information missing when you show the transaction history 

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#313]
![image](https://user-images.githubusercontent.com/65085660/105614902-75f0e380-5d9a-11eb-8df3-2e37a8721888.png)
payment information not showing in the history when u show it from the patient's profile

**Comment by nidhirbstpl** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/ff4b5c8e07d533baaad9243d890c9b0128686551
