### ISSUE TITLE
[FEATURE-REQ] Onboarding changes

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#315]
- WL_Stores needs password col
- Login page checks WL_Stores for login and token assignment

- WL_Users are for all users
- add PIN column for WL_Users (optional string)
- Owner portal creates users and assigns stores via WL_StoreUserLink and WL_Users
- Owner portal assigns permissions to users via WL_StoreUserLink 

- if user is pharmacist the isPharmacist column must reflect that
- password is not optional for pharmacists

- Owners create temporary PIN for pharmacists, upon login for pharmacists, have dialog that triggers to have pharmacist create a password (stored securely), and the temporary PIN is removed
- PINs must be unique within a store
- PINs are verified locally
- PINs are 4 digits only
- WL_StoreUserLink  also stores the PIN for that user for that store

- Front end need to grab all the users associated with a store upon login (WL_Users and WL_StoreUserLink)

- Owner portal querying all stores and users: Wl_Stores queried by OWNER_ID, [...STORE_IDs] used to query WL_StoreUserLink, [...USR_IDs] used to query WL_Users
- same thing on frontend but starting with STORE_ID

**Comment by pwang-boxlabs** [comment]
https://docs.google.com/document/d/1YqTX1I2E6uLQoXPJBBhGnwWDZkh_5qtatNXwciNZjt8/edit
