### ISSUE TITLE
[URGENT] amount due in change disappears too quickly - 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#326]
simple solution to this is to just add amount of change due from the previous transaction under the orders section on the main page

**Comment by dyuan-boxlabs** [comment]
im not sure what this means, amount due is always displayed at the bottom and at the right hand side even before you submit the transaction

![image](https://user-images.githubusercontent.com/65084919/107786561-0c6e5000-6d1c-11eb-8034-e6e6df9caf43.png)
