### ISSUE TITLE
permission check to give user diff access

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#328]
permission can be foudn in ducks: auth/permissions

Admin: false, -- access to everything 
Sale: false, -- pos
Inventory: false -- ediiting product
System: false, -- setting information
Reports: false -- needs this to access reports

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/2892f74991a090146f39800438e00d3f56772e5d
