### ISSUE TITLE
[FEATURE-REQ] add date of purchase

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#33]
Need to display date of purchase as first item in column here

![image](https://user-images.githubusercontent.com/61169385/89329339-aa41dd80-d65c-11ea-8ecb-b622a9037c7a.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/37
