### ISSUE TITLE
dialog to edit Rx

### ISSUE THREAD

**Issue by pwang-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#332]
![image](https://user-images.githubusercontent.com/65085660/107702212-eac38900-6c87-11eb-8df9-cc45aff769db.png)
should be able to edit rx info here.  i.e. change status

**Comment by nidhirbstpl** [comment]
Fix in 
https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/76d8e8c727dcb3a3fca92f9db899ba565a5f773f
https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/fb4d4e83750d170d177bc3137d4a609c90900c1c
