### ISSUE TITLE
[BUG] Tooltip not removed once cursor moves away

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#337]
![image](https://user-images.githubusercontent.com/65084919/107902636-0c857000-6f15-11eb-958c-c3c8ca7351b0.png)

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/359/commits/ccd817ad23fc36e5581f9120f446214bb9cb7aab
