### ISSUE TITLE
[FEATURE-REQ] Cancel & Delete RX

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#349]
there needs to be a button or the three dots at the end of the drug called "REVERSE AND REMOVE RX" which will reverse the billing and remove the RX from the profile (for expanded services) - if something is incorrectly billed.
 
![image](https://user-images.githubusercontent.com/61169385/108222761-1242a780-7107-11eb-8a06-95d146d99af1.png)

**Comment by mikedemian** [comment]
Also please add column for RX number here

![image](https://user-images.githubusercontent.com/61169385/108226053-87fc4280-710a-11eb-86a1-0ac58035955f.png)

**Comment by mikedemian** [comment]
also replace RX_ID with RX# here

![image](https://user-images.githubusercontent.com/61169385/108226735-2a1c2a80-710b-11eb-8859-b3a0f49cf616.png)

**Comment by dyuan-boxlabs** [comment]
reverse from patient details is tracked in this ticket https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/350

**Comment by nidhirbstpl** [comment]
Fix in 
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/366/commits/9ec1dd868ce2ecd01529292bfacc4b9642a5a378
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/366/commits/936f8711842826c0930f074cce282e42d6711dca
