### ISSUE TITLE
[BUG] Cash Open - App Closed - Asked to Open Cash again

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#35]
When you "Open Cash" by entering amount in the register and exit the APP - if you have not "closed" the cash it should not ask you to open it again - it should just alert you saying Cash previously opened at "X date and time" and has not yet been closed - click ok to confirm

**Comment by pwang-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/38
