### ISSUE TITLE
[FEATURE-REQ] basic adjudication UI clean up for demos - HIGH PRIORITY

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#357]
![image](https://user-images.githubusercontent.com/61169385/108453880-5a61e700-7239-11eb-9d36-45eb0b9dc596.png)

remove unnecessary fields - response should just be ACCEPTED , or REJECTED - with reason so we can resbmit 

Only needed fields are health card number, carrier, and intervention codes - nothing else is needed ; also can you make window a little smaller - I want to demo this in a week so i'd like it to look half way decent.

**Comment by nidhirbstpl** [comment]
Fix in 
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/370
