### ISSUE TITLE
[BUG] Lag when switching between patients where it shows the old patient for a few seconds

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#36]
There is a lag when switching between patients where it shows the old patient for a few seconds  - its better if it shows nothing because users start interacting as they think its loaded but its not the correct patient - if this is confusing please ask me.

**Comment by dyuan-boxlabs** [comment]
on code tip there is a loading reticle that prevents interaction when patient is loading
