### ISSUE TITLE
[BUG] tooltip still floating 

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#363]
![image](https://user-images.githubusercontent.com/65084919/108630820-ca888c80-7434-11eb-9f07-04dc6c5eb96e.png)

1) click patient tab
2) move mouse out of side menu quickly
3) tooltip floats

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/381
