### ISSUE TITLE
[FEATURE-REQ] Status , Picked Up - Redundant fields

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#37]
**Describe the solution you'd like**
There doesn't need to be two columns for status and picked up - they are the same thing - the status is just where the RX is in the process - for now the only two status will be "Ready" , "Picked Up (with date and time attached)"

![image](https://user-images.githubusercontent.com/61169385/89331000-0efe3780-d65f-11ea-84fb-02b4fdd97f4c.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/39
