### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by nancydemian** [BoxLabsGithub/CubePharmacyPublicReleases#39]
**Nancy Demian:**
 - Bathurst
 - Ricci,Vilma
 - Medscheck

**Describe the bug**
Upon completing the Medscheck, Once I hit "Finalize and Sign" it gives me an error message "Something went wrong! Please restart the app."

**To Reproduce**
1. Go to her medscheck that is saved 
2. Click on finalize and sign
3. See Error

**Expected behavior**
I should be able to have the patient sign on the next page and have me sign so i can complete the medscheck

![error](https://user-images.githubusercontent.com/69218312/89342317-9ef8ad00-d670-11ea-97aa-9fdc56d15bb8.png)

**Comment by pwang-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/32/commits/5f9cc41ec9a1ef7e0f2d2bf5e9d47d4c4fde6850
