### ISSUE TITLE
[BUG] Medscheck - none of these buttons work - see image

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#40]
None of the options in this drop down currently work 

Download PDF
Print PDF
.... if a medscheck is complete it should not allow you to "Continue" instead it should be "Modify" 

![image](https://user-images.githubusercontent.com/61169385/89417678-fd6b6d00-d6fc-11ea-8765-b840f0a766e1.png)

**Comment by nidhirbstpl** [comment]
Yes, Only "Continue" is implemented as of now and working fine.
Please provided comments here that what actions should be implemented for "View" and how it should look.
Also Download PDF have some issue and not working properly.

**Comment by dyuan-boxlabs** [comment]
View, Continue, Print, Download PDF will be reduced to Modify/Continue (depending on if the medscheck is completed or not", Download PDF

**Comment by dyuan-boxlabs** [comment]
Right now, we get the PDF from clicking the button in the image below, and then "View Image" next to it which initiate electron.openShell(), this will be changed to initiate the file download procedure dialog on the OS. Same behavior for the button Download PDF above.

![image](https://user-images.githubusercontent.com/65084919/89551436-f31ea100-d7d8-11ea-9a82-4f5ca2b590d0.png)

**Comment by nidhirbstpl** [comment]
I have setup pdftk on system , but creating pdf is still not working.
