### ISSUE TITLE
[FEATURE-REQ] low priority - settle account should probably lead to POS screen instead of using the dialog

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#43]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/17
settle patient account uses dialog, should probably lead to POS screen for consistency

**Describe alternatives you've considered**

**Additional context**

**Comment by mikedemian** [comment]
This isn’t really low priority. Needs to be fixed ASAP as it’s a function that’s frequency used. No way to settle any patients account.
