### ISSUE TITLE
Patient Search - in POS Patient Search

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#52]
Why does this only show 10 patient names, can we increase that to 20? as sometimes patient you are looking for isn't there until you enter more characters.

![image](https://user-images.githubusercontent.com/61169385/89932386-8f7ee400-dbdb-11ea-8f6f-1a2714abb80f.png)

**Comment by pwang-boxlabs** [comment]
@nidhirbstpl  the this is caused by the autosizer and this only happens in production. Please take a look. The bottom pagination is always hidden in production for some reason

**Comment by nidhirbstpl** [comment]
@pwang-boxlabs now it shows show 20 patients in table. The bottom pagination requires some lay-outing work, I will fix soon
