### ISSUE TITLE
We need a "MEDSCHECK COMPLETE" page

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#53]
its confusing that when you finish a medscheck this is what comes up- because you can go back and modify and it just doesn't look like you are done. Suggesting a simple "medscheck completed" page with the same options as are listed here.

![image](https://user-images.githubusercontent.com/61169385/89934425-893e3700-dbde-11ea-9588-25733548c228.png)

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/70/commits/c232508d269f609ecd2c2b383c4d62a516df4daf

![Screen Shot 2020-08-26 at 10 46 04 PM](https://user-images.githubusercontent.com/32067907/91338188-2f4e8b80-e7f2-11ea-9194-41e052ef320d.png)

**Comment by nidhirbstpl** [comment]
Incorporated review comments in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/72/commits/2a2359de3b4e6e225a117f23135e4f0d4a2f02cf

![Screen Shot 2020-08-27 at 9 27 40 PM](https://user-images.githubusercontent.com/32067907/91466037-320db700-e8ac-11ea-9add-050d9723c6c0.png)
