### ISSUE TITLE
MEDSCHECK - remove drugs after selecting

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#56]
**Is your feature request related to a problem? Please describe.**
If you add a drug to go over during medscheck there is no way to remove that drug if you go to the next screen. So if you accidently add one you can't go back and remove it.

**Describe the solution you'd like**
Be able to go back and remove it

**Comment by dyuan-boxlabs** [comment]
fixed on latest
