### ISSUE TITLE
If Scan one RX in a batch add all others

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#58]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when we have to scan 10 plus rx's for one patient one at a time, or if a patient has a bunch of RX to add to POS

**Describe the solution you'd like**
when one rx is scanned out ask user if they would like to add all other RX's that were filled that day

**Comment by dyuan-boxlabs** [comment]
dependent on https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/63

**Comment by dyuan-boxlabs** [comment]
redundant, we add from unpicked up rx
