### ISSUE TITLE
DIN shows up but no drug info for this patient 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#6]
![image](https://user-images.githubusercontent.com/61169385/88684133-831a6780-d0c2-11ea-998c-7c03abf29004.png)

**Comment by dyuan-boxlabs** [comment]
02244078 is dimetapp-c, NOT present on the ontario drug xml db. Need to address the following:

- do we need to worry about drugs on Canadian Drug Database but not present on Ontario benefits xml? I'm guessing this is leaning towards yes as private insurance companies might cover drugs thats not on the ODB benefits db.

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/27
