### ISSUE TITLE
[BUG] Change Quantity on POS

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#62]
**User information:**
 - Store login name: [e.g. user_Bathurst, user_Church]
 - Patient name (if applicable)
 - Rx number (if applicable)

**Describe the bug**
Change quantity does not work from three dots at all and it only works from top button for increasing quantity, you can't change 2 to 1. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pwang-boxlabs** [comment]
can you make sure the item is not a rx prescription? i can't reproduce the error but you can't change the quantity of an RX

**Comment by pwang-boxlabs** [comment]
can't reproduce it. are you able to reproduce it consistently?
