### ISSUE TITLE
[BUG] Remove false CC info in refund dialog

### ISSUE THREAD

**Issue by dyuan-boxlabs** [BoxLabsGithub/CubePharmacyPublicReleases#65]
**User information:**
 - Store login name: [e.g. user_Bathurst, user_Church]
 - Patient name (if applicable)
 - Rx number (if applicable)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
![image](https://user-images.githubusercontent.com/65084919/90418854-b3cb3c80-e083-11ea-8bb0-96faaa42f288.png)

**Comment by nidhirbstpl** [comment]
Fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/61/commits/ac185454dc59028a89ca9c30927568678c80cf6d
