### ISSUE TITLE
[BUG] price shown for RX is not correct

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#67]
**User information:**
 - Store login name: user_Bathurst
 - Patient name : Olga Soares
 - Rx number 1285192

**Describe the bug**
Price shown when scanned is the total price of the RX - but not what patient pays - patients pays in this case is zero. (0.00) on the RX receipt is ZERO.

![image](https://user-images.githubusercontent.com/61169385/90438425-f0a62c00-e0a1-11ea-8827-725ebf4880e6.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/5ed30b93e9b7952652855c7a31b7fac4d8557960
