### ISSUE TITLE
[BUG] Search not working properly

### ISSUE THREAD

**Issue by nancydemian** [BoxLabsGithub/CubePharmacyPublicReleases#71]
**User information:**
 - Store login name: Bathurst

Issue is self evident if you look at screenshot - unable to find patient when searched

![image](https://user-images.githubusercontent.com/69218312/90440326-0b2dd480-e0a5-11ea-82c6-b922b59563f7.png)

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/62
