### ISSUE TITLE
[FEATURE-REQ] Patient Communications - Tab

### ISSUE THREAD

**Issue by nancydemian** [BoxLabsGithub/CubePharmacyPublicReleases#72]
Additional tab for patient communication -

Detailed account of what happens each time patient calls or doc calls on behalf of patient so that user can easily see trail of events 

UI to follow ***

![image](https://user-images.githubusercontent.com/69218312/90441338-c73bcf00-e0a6-11ea-99d7-3486ab077385.png)

**Comment by dyuan-boxlabs** [comment]
need further clarification

**Comment by dyuan-boxlabs** [comment]
Add a jsonb column to WL_Pats (production and dev), default to empty array, non-null

use modifyPatient action dispatcher to write to this column

add another tab in Rx history etc. for patient notes

patient notes would be a table with a button to add notes

the jsonb data shape should include the note itself, date created, user_id, records are not editable
