### ISSUE TITLE
OTC Scan always 2 items

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#73]
**User information:**
 - Store login name: user_Dundas

**Describe the bug**
All OTC items scan to two items at Dundas

![image](https://user-images.githubusercontent.com/61169385/90525179-f8ff7500-e13c-11ea-98d6-63b4f87944dc.png)

**Comment by mikedemian** [comment]
064562312308
see above the barcode for the item

**Comment by dyuan-boxlabs** [comment]
is upc / patients searchbar is infocus, then this gets added twice
