### ISSUE TITLE
[FEATURE-REQ] Dialog box questions and answers need to be clear

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#75]
Answer to this question should be Yes-back to Profile or No- Continue Medscheck.  -
![image](https://user-images.githubusercontent.com/61169385/90650689-2b2ad880-e20a-11ea-8027-511a54698550.png)

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/70/commits/3d96a9db1920da324980795df7b6003f7d7b633a

![Screen Shot 2020-08-26 at 10 46 04 PM](https://user-images.githubusercontent.com/32067907/91338450-966c4000-e7f2-11ea-83e9-823bc3cf16d7.png)
