### ISSUE TITLE
[BUG] person finishing using debit machine and was still stuck on this screen

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#77]
Also since most recent update it no longer goes back to original POS screen after you hit Complete Order.
 
![image](https://user-images.githubusercontent.com/61169385/90684622-8672c000-e236-11ea-94ff-76d4af590610.png)

**Comment by dyuan-boxlabs** [comment]
cannot replicate, remoted in dundas and this works
