### ISSUE TITLE
Indication for Drug Not Included in Medscheck!

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#78]
This was on the UI but not included in the medscheck created. The indication (reason for taking) needs to be included.

In the same way that Box auto-saves pharmacist entries for other fields it should do the same for this - however it should be linked to the DRUG - so for a specific DRUG (and its interchangeable) it should list indications that have been previously entered.

![image](https://user-images.githubusercontent.com/61169385/91186608-40e24700-e6bd-11ea-8b69-71bdf5da9739.png)

**Comment by mikedemian** [comment]
Please see this image with update updated section for Indication  - please put it above the Add Patients Comments
![image](https://user-images.githubusercontent.com/61169385/91322801-24620f80-e78e-11ea-9a81-7dada3744405.png)

this is 100% user entry - the results should not show the next time they are filling out a medscheck like the other fields but it should be saved somewhere in our system for future use.

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/72/commits/5618712f62342b7d4d0d25601ebebc03e5ea9222

![Screen Shot 2020-08-27 at 8 07 19 PM](https://user-images.githubusercontent.com/32067907/91466609-02ab7a00-e8ad-11ea-8729-f9109c02c49d.png)
