### ISSUE TITLE
Same Drug Shows up Multiple Times

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#8]
![image](https://user-images.githubusercontent.com/61169385/88684690-1d7aab00-d0c3-11ea-95a9-6d6014e11b5c.png)
![image](https://user-images.githubusercontent.com/61169385/88684711-22d7f580-d0c3-11ea-82e4-de748a04dd2f.png)

why is this patient have the same drug show up multiple times on medscheck

**Comment by dyuan-boxlabs** [comment]
fixed in https://github.com/BoxLabsGithub/CubePharmacy-TS3/pull/23
