### ISSUE TITLE
[FEATURE-REQ] gray out all non-usable buttons and items and reports 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#84]
gray out all non-usable buttons and items and reports

**Comment by nidhirbstpl** [comment]
![Screen Shot 2020-08-28 at 6 44 46 PM](https://user-images.githubusercontent.com/32067907/91589291-17ecdb00-e977-11ea-852d-99a0362e2e12.png)
![Screen Shot 2020-08-28 at 8 56 57 PM](https://user-images.githubusercontent.com/32067907/91589299-1c18f880-e977-11ea-90e9-5f86816e1107.png)
