### ISSUE TITLE
[BUG] Sales & Tax Summary Report 

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#86]
![image](https://user-images.githubusercontent.com/61169385/91211329-9bd76680-e6dc-11ea-8e40-3d9140c51030.png)

Average transaction (#items) - should be (amount of items in each POS transaction)/(total number of POS transactions)
RX Purchase Cost is not factored in - not sure why - that would be the K&F/McKesson price

Total Selling Cost for NON-RX is not showing up - not sure why.

Total RX Brand /Generic sales is not correct

and of course gross profit (%) is not factored in

**Comment by nidhirbstpl** [comment]
As of now showing as follow 
"Average Transaction ($)" is calculated as = total amount / (total number of POS transactions)
"Purchase Cost" = cost
Total Selling Cost = subtotal
gross profit (%) = rxOrders avgProfitPct

**Comment by dyuan-boxlabs** [comment]
need verification, fix for this was pushed yesterday (was missing rx costs) @mikedemian
