### ISSUE TITLE
[FEATURE-REQ] Last Purchase date is N/A - why?

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#88]
![image](https://user-images.githubusercontent.com/61169385/91213443-9b8c9a80-e6df-11ea-9462-3a8024ccdc8a.png)

see this image

**Comment by pwang-boxlabs** [comment]
@mikedemian  have you made any purchases with this account? it's n/a if no purchases have been made

**Comment by mikedemian** [comment]
Yes I have - you can see transaction history and purchase history

![image](https://user-images.githubusercontent.com/61169385/91302656-cecd3900-e774-11ea-8c04-88626f253c12.png)
