### ISSUE TITLE
[FEATURE-REQ] Back to Profile

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#9]
When you click on the patient search icon on the left tool bar it should default back to the last patient - if that is not possible then the list that shows up should be in reverse order (from most to least recent) of patients whose profiles you have opened.

**Comment by dyuan-boxlabs** [comment]
https://github.com/BoxLabsGithub/CubePharmacyPublicReleases/issues/135 redundant
