### ISSUE TITLE
[FEATURE-REQ] % discount on item

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#90]
![image](https://user-images.githubusercontent.com/61169385/91215728-e78d0e80-e6e2-11ea-83a6-198d94e47c17.png)

why can't you add a % discount on items?

**Comment by dyuan-boxlabs** [comment]
in redux POS store the discount value is in dollars, keep it as dollars

The percentage entered should be kept in state only on the UI level (as a React.state)
