### ISSUE TITLE
[BUG] Report Customer Statement

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#92]
Dundas 

![image](https://user-images.githubusercontent.com/61169385/91305644-5157f780-e779-11ea-8c31-f8c1d87f07e9.png)

Incorrect address information shown at the top left

Also does not show items that have been paid for should show all items paid and owed for the customer.

**Comment by pwang-boxlabs** [comment]
we can't really tell which items are paid are not. it works like credit card systems --  the granularity is to transaction instead of item.

**Comment by nidhirbstpl** [comment]
Fix in https://github.com/BoxLabsGithub/CubePharmacy-TS3/commit/c5ae7f392381138a61825d7c3829dee7ae6cbf3f
