### ISSUE TITLE
[FEATURE-REQ] Forms - Pharm Opinion, Flu Shot, FOD

### ISSUE THREAD

**Issue by mikedemian** [BoxLabsGithub/CubePharmacyPublicReleases#99]
Please see this link  https://www.figma.com/file/QunL8IFHemia55u0RdRYn8/Questionnaires?node-id=0%3A1

it will be updated slightly the UI for these forms is essentially done - to get to these screens from either the patient profile or the POS.

**Comment by nidhirbstpl** [comment]
![Screen Shot 2020-09-03 at 9 49 00 PM](https://user-images.githubusercontent.com/32067907/92266087-184c1f80-eefd-11ea-9d8b-73ed07f00335.png)

**Comment by nidhirbstpl** [comment]
Design work : - Consent Given By Patient.

![Screen Shot 2020-09-07 at 8 15 13 PM](https://user-images.githubusercontent.com/32067907/92438068-c558bd80-f1c5-11ea-8ac4-12d759edfd47.png)

**Comment by nidhirbstpl** [comment]
UI work for:  "Prescription Templates – Pharmacy Use Only"

![Screen Shot 2020-09-08 at 6 34 23 PM](https://user-images.githubusercontent.com/32067907/92480156-27371880-f202-11ea-95a7-26d056bf6690.png)


![Screen Shot 2020-09-08 at 6 34 39 PM](https://user-images.githubusercontent.com/32067907/92480181-2d2cf980-f202-11ea-9d91-f07c418aa340.png)
